markdown: redcarpet
baseurl: ""
exclude: ["README.md", "Gemfile", "Gemfile.lock"]
title: JPCMarques' personal website
theme: jekyll-theme-cayman
permalink: pretty
repository: JPCMarques/JPCMarques.github.io.git
sass:
    sass_dir: _sass
    style: compressed

collections:
    nav-headers:
      output: true
