markdown: kramdown
highlighter: rouge
baseurl: ""
exclude: ["README.md", "Gemfile", "Gemfile.lock", "_apps/rsappcentral.md"]
title: JPCMarques' personal website
theme: jekyll-theme-cayman
permalink: pretty
repository: JPCMarques/JPCMarques.github.io.git
sass:
    sass_dir: _sass
    style: compressed
collections:
    study-wiki:
        output: true
        permalink: study-wiki/:path/
    apps:
        output: false
    light-novels:
        output: true
        permalink: /light-novels/:path/
    expanded-universe:
        output: true
        permalink: /light-novels/expanded-universe/:path/
    book-reviews:
        output: true
        permalink: /book-reviews/:path/
    main-pages:
        output: true
        permalink: /:title/
