markdown: kramdown
baseurl: ""
exclude: ["README.md", "Gemfile", "Gemfile.lock", "_apps/rsappcentral.md"]
title: JPCMarques' personal website
theme: jekyll-theme-cayman
permalink: pretty
repository: JPCMarques/JPCMarques.github.io.git
sass:
    sass_dir: _sass
    style: compressed
collections:
    study-wiki:
        output: true
    apps:
        output: false
    light-novels:
        output: true
        permalink: /light-novels/:title/
    world-building:
        output: true
        permalink: /light-novels/:title/world-building/
    enterprise-integration:
        output: true
        permalink: /study-wiki/enterprise-integration/:title/
    data-administration-in-information-systems:
        output: true
        permalink: /study-wiki/data-administration-in-information-systems/:title/
    cloud-computing-and-virtualization:
        output: true
        permalink: /study-wiki/cloud-computing-and-virtualization/:title/